name: CostBot Continuous Integration

on: [push, pull_request]

jobs:
    ts:
        name: TypeScript
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to repository
              uses: actions/checkout@v2
            - name: Configure files
              run: mv src/botconfig-example.ts src/botconfig.ts | mv .env.example .env
            - name: Setup Node.js v14
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: 14
            - name: Install dependencies
              run: npm ci
            - name: Run TypeScript Compiler
              uses: icrawl/action-tsc@v1
    lint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to repository
              uses: actions/checkout@v2
            - name: Configure files
              run: mv src/botconfig-example.ts src/botconfig.ts | mv .env.example .env
            - name: Setup Node.js v14
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: 14
            - name: Install dependencies
              run: npm ci
            - name: Run ESLint
              uses: icrawl/action-eslint@v1
